### PR TITLE
!!! fixed typo

### PR DESCRIPTION
**Pull request by UVLabs**
Please also update the zipfile here: http://bit.ly/themeisle-pirate-parrot

### CODE REVIEW

**Comment by UVLabs** [comment]
@rodica-andronache @ineagu

**Comment by rodica-andronache** [comment]
@UVLabs thanks :) I don't think you need to mention ionut in commits like this, only if it's really necessary

**Comment by UVLabs** [comment]
Understood.

**Comment by rodica-andronache** [comment]
@selu91 can you please update the zip file when you have time? :)

**Pull request merged**
